version: "3.9"

services:
  mails-generator-service:
    build:
      context: .
      dockerfile: ./mails-generator-server/Dockerfile
    ports:
      - 8000:8000

  frontend-service:
    build:
      context: .
      dockerfile: ./front/Dockerfile
    ports:
      - 8501:8501
    depends_on:
      - mails-generator-service
