version: "3.9"

services:
  main-service:
    build:
      context: .
      dockerfile: ./main-server/Dockerfile
    ports:
      - 8001:8001
    environment:
      - PYTHONUNBUFFERED=1

  mails-generator-service:
    build:
      context: .
      dockerfile: ./mails-generator-server/Dockerfile
    ports:
      - 8000:8000
    environment:
      - PYTHONUNBUFFERED=1

  mails-sender-service:
    build:
      context: .
      dockerfile: ./mails-sender-server/Dockerfile
    ports:
      - 8002:8002
    environment:
      - PYTHONUNBUFFERED=1

  frontend-service:
    build:
      context: .
      dockerfile: ./front/Dockerfile
    ports:
      - 8501:8501
    depends_on:
      - mails-generator-service
    environment:
      - PYTHONUNBUFFERED=1
