def getMailHeader(companyName):
    return "I am a company named " + companyName + ","


# What is your business about?, here thr peoblem is generated by the chatgpt
def getBiggestUsersProblemMailStr(companyName, businessAbout):
    str = getMailHeader(companyName)
    str += (
        " Write me an email to my costumers about the biggest problem faced by customers who want to "
        + businessAbout
    )
    str += " and add a practical tip  on how to deal with the problem"

    return str


def getTrendsInFieldMailStr(companyName, businessAbout):
    str = getMailHeader(companyName)
    str += " Write me an email to my costumers about the trends in " + businessAbout
    str += ", and explain to me why these trends are so popular"

    return str


def getThreeWaysToSolveProblemMailStr(companyName, businessAbout):
    str = getMailHeader(companyName)
    str += " Write me an email about the biggest problem in " + businessAbout
    str += ", and give me 3 ways to deal with the problem today with an explanation"

    return str


def getClientsDreamMailStr(companyName, clientsDream):
    str = getMailHeader(companyName)
    str += " The biggest dream of my clients is " + clientsDream
    str += ", write me an email about the subject as the hero's story"

    return str


def getClientsAvoidMailStr(companyName, clientsAvoid):
    str = getMailHeader(companyName)
    str += (
        " my clients avoid "
        + clientsAvoid
        + " write me an email about the problem and how it can be easily solved"
    )

    return str


def getClients23waysToSolveClientsProblemMailStr(companyName, clientsProblem):
    str = getMailHeader(companyName)
    str += " Write me an email with 23 tips for the problem " + clientsProblem
    return str


def getClientsFeedbackMailStr(companyName, businessAbout):
    str = getMailHeader(companyName)
    str += (
        " Write me an email asking my clients what they want to receive future content from me, my clients are interested in "
        + businessAbout
    )
    str += " tell the subjects and at the end ask them what subjects they want to receive information from me in the future"

    return str


def getStoryTellingAboutClientsProblemMailStr(companyName, clientsProblem):
    str = getMailHeader(companyName)
    str += " Write me a storytelling email about " + clientsProblem
    str += " the story should contain the problem and inspiration to solve the problem"

    return str


def get3RecommendedBooksMailStr(companyName, businessAbout):
    str = getMailHeader(companyName)
    str += (
        " Write me an email about 3 recommended books for my clients in the "
        + businessAbout
        + " field"
    )
    str += " the email should sound as if I read the books and why I recommend them"

    return str


def get3InternationalExpertMailStr(companyName, businessAbout):
    str = getMailHeader(companyName)
    str += (
        " Write me an email with 5 tips from an international expert on "
        + businessAbout
    )
    str += " write the email in a cute and funny way"

    return str


def addToStrAnInfluencerStyle(mailStr, influencer):
    mailStr += ", in " + influencer + " style"

    return mailStr


def getAllPrompts(
    companyName,
    businessAbout,
    clientsDream,
    clientsAvoid,
    clientsProblem,
):
    prompts = []

    prompts.append(getBiggestUsersProblemMailStr(companyName, businessAbout))
    prompts.append(getTrendsInFieldMailStr(companyName, businessAbout))
    prompts.append(getThreeWaysToSolveProblemMailStr(companyName, businessAbout))
    prompts.append(getClientsDreamMailStr(companyName, clientsDream))
    prompts.append(getClientsAvoidMailStr(companyName, clientsAvoid))
    prompts.append(
        getClients23waysToSolveClientsProblemMailStr(companyName, clientsProblem)
    )
    prompts.append(getClientsFeedbackMailStr(companyName, businessAbout))
    prompts.append(
        getStoryTellingAboutClientsProblemMailStr(companyName, clientsProblem)
    )
    prompts.append(get3RecommendedBooksMailStr(companyName, businessAbout))
    prompts.append(get3InternationalExpertMailStr(companyName, businessAbout))

    return prompts
